services:
  php:
    build:
      context: ../lib_main1/docker/php
    container_name: symfony_php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
    networks:
      - symfony_network
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony_network
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: symfony_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfonymysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - symfony_network

volumes:
  mysql_data:

networks:
  symfony_network:
    driver: bridge
